use super::ip::Port;

// I want the window smaller for debugging
#[cfg(debug_assertions)]
pub const WORKSPACE_WINDOW_WIDTH: f32 = 880.0;
#[cfg(debug_assertions)]
pub const WORKSPACE_WINDOW_HEIGHT: f32 = 1080.0;

#[cfg(not(debug_assertions))]
pub const WORKSPACE_WINDOW_WIDTH: f32 = 1450.0;
#[cfg(not(debug_assertions))]
pub const WORKSPACE_WINDOW_HEIGHT: f32 = 1080.0;

pub const DEFAULT_WINDOW_STARTING_POS: eframe::epaint::Pos2 = eframe::epaint::Pos2 {
    x: WORKSPACE_WINDOW_WIDTH / 2.0 - 150.0,
    y: WORKSPACE_WINDOW_HEIGHT / 2.0 - 150.0,
};

#[cfg(windows)]
pub const LINE_ENDING: &str = "\r\n";
#[cfg(not(windows))]
pub const LINE_ENDING: &str = "\n";

pub const DEFAULT_SPACER: f32 = 5.0;
pub const ACTION_SPACER: f32 = 10.0;

pub const TRASH_ICON: &str = "🗑";

pub const MOST_COMMON_PORTS: [Port; 7] = [13, 22, 23, 80, 443, 8080, 8443];

// TODO: Fill with data from + filter out pointless ports:
// https://docs.oracle.com/en/database/oracle/oracle-database/18/rilin/port-numbers-and-protocols-of-oracle-components.html#GUID-D168F70C-BECE-4F9A-B616-D9103A35F1FF
// https://docs.oracle.com/cd/E36909_01/core.1111/e10105/portnums.htm
// https://developer.hashicorp.com/consul/docs/agent/config/config-files#ports
// https://help.sap.com/docs/Security/575a9f0e56f34c6e8138439eefc32b16/616a3c0b1cc748238de9c0341b15c63c.html
// https://www.speedguide.net/ports_sg.php?page=1&sort=&category=&seek=
// https://nullsec.us/top-1-000-tcp-and-udp-ports-nmap-default/ <--- make sure all top 1000 are included here
pub const ALL_COMMON_PORTS_LENGHT: usize = 420;
// Port , Protocol , Usefull info
pub const ALL_COMMON_PORTS: [(Port, &str, &str); ALL_COMMON_PORTS_LENGHT] = [
    // Well-known/System ports: 0 – 1023
    (1, "tcpmux", "Scans against this port are commonly used to test if a machine runs SGI Irix (as SGI is the only system that typically has this enabled). This service is almost never used in practice. ; RFC1078 - TCPMUX acts much like Sun's portmapper, or Microsoft's end-point mapper in that it allows services to run on arbitrary ports. In the case of TCPMUX, however, after the \"lookup\" phase, all further communication continues to run over that port."),
    (2, "compressnet", "Port 2 is also registered with IANA for compressnet management utility."),
    (3, "compressnet", "Midnight Commander Sometimes this program is assigned to this port"),
    (4, "sfs", "Self-Certifying File System(SFS) sfssd acceps connections on TCP port 4 and passes them to the appropriate SFS daemon. SFS is a secure, global file system with completely decentralized control. SFS uses NFS 3 as the underlying protocol for file access."),
    (5, "rje", "Remote Job Entry"),
    (7, "Echo", "Echo service"),
    (9, "Discard", "Discard server - this protocol is only installed on machines for test purposes. The service listening at this port (both TCP and UDP) simply discards any input."),
    (10, "misc", "AT&T 5268ac router may listen on port 10 TCP"),
    (11, "systat", "On some UNIX machines, creating a TCP connection to this port will dump the active processes and who launched them. The original intent for this was to make remote management of UNIX easier. However, intruders will query the systat information in order to map out the system."),
    (15, "netstat", "Port used by netstat (a variant of systat, see port 11). Rarely available because of security concerns. It can be used to list active processes and who launched them on some UNIX machines."),
    (19, "CHARGEN", "Character Generator Protocol, has severe vulnerabilities and thus is rarely used nowadays"),
    (20, "FTP-data", "File Transfer Protocol data transfer"),
    (21, "FTP", "File Transfer Protocol command control"),
    (22, "SSH/SCP/SFTP", "Secure Shell, secure logins, file transfers (scp, sftp), and port forwarding"),
    (23, "Telnet", "Telnet protocol, for unencrypted text communications"),
    (24, "priv-mail", "Port used by any private mail system"),
    (25, "SMTP", "Simple Mail Transfer Protocol, used for email routing between mail servers"),
    (26, "rsftp", "Port used by RSFTP - a simple FTP-like protocol. Sometimes also used as an alternate to port 25 SMTP (Simple Mail Transfer Protocol)"),
    (34, "remote", "Remote File (RF) - used for file transfer between machines"),
    (38, "rap", "Route Access Protocol (IANA official)"),
    (42, "WINS Replication", "Microsoft Windows Internet Name Service, vulnerable to attacks on a local network"),
    (43, "WHOIS", "Whois service, provides domain-level information"),
    (49, "TACACS", "Terminal Access Controller Access-Control System, provides remote authentication and related services for network access"),
    (51, "Possibly VPN", "Some vpns use this port"),
    (53, "DNS", "Domain Name System name resolver"),
    (65, "TACACS-DS", "TACACS-Database Service (IANA official)"),
    (67, "DHCP/BOOTP", "Dynamic Host Configuration Protocol and its predecessor Bootstrap Protocol Server; server port"),
    (68, "DHCP/BOOTP", "Dynamic Host Configuration Protocol and its predecessor Bootstrap Protocol Server; client port"),
    (69, "TFTP", "Trivial File Transfer Protocol"),
    (70, "Gopher", "Gopher is a communication protocol for distributing, searching, and retrieving documents in Internet Protocol (IP) networks"),
    (77, "priv-rje", "IANA assigned for any private RJE service, netjrs. The error message \"TK_SPACE undeclared\" is common to this port. This occurs when installed ports keep bombing out on sqlite3."),
    (79, "Finger", "Name/Finger protocol and Finger user information protocol, for retrieving and manipulating user information"),
    (80, "HTTP", "Hypertext Transfer Protocol (HTTP) uses TCP in versions 1.x and 2. HTTP/3 uses QUIC, a transport protocol on top of UDP"),
    (81, "HTTP", "Hypertext Transfer Protocol (HTTP) uses TCP in versions 1.x and 2. HTTP/3 uses QUIC, a transport protocol on top of UDP"),
    (84, "ctf", "Common Trace Facility (IANA official)"),
    (88, "Kerberos", "Network authentication system"),
    (92, "npp", "Network Printing Protocol (IANA official)"),
    (93, "dcp", "Device Control Protocol (IANA official)"),
    (101, "hostname", "Hostnames NIC Host Name Server. [RFC953] [RFC811]"),
    (102, "Microsoft Exchange ISO-TSAP", "Microsoft Exchange ISO Transport Service Access Point (TSAP) Class 0 protocol"),
    (103, "gppitnp", "MS Exchange X.400 mail messaging traffic"),
    (109, "POP2", "Post Office Protocol 2 (obsolete). While POP2 has largely been replaced by POP3, hackers still scan for this port because many older POP servers have vulnerabilities associated with them. [RFC937]"),
    (110, "POP3", "Post Office Protocol, version 3 (POP3)"),
    (111, "SunRPC", "Provides information between Unix based systems. Port is often probed, it can be used to fingerprint the Nix OS, and to obtain information about available services. Port used with NFS, NIS, or any rpc-based service."),
    (113, "Ident", "Identification Protocol, for identifying the user of a particular TCP connection"),
    (119, "NNTP (Usenet)", "Network News Transfer Protocol"),
    (123, "NTP", "Network Time Protocol"),
    (125, "misc", "Port is sometimes unofficially used as an alternate to port 25 SMTP (Simple Mail Transfer Protocol). This is useful as a dedicated port for VPN clients or for those who cannot directly send mail to a mail server outside of their ISP's network because of an ISP block on port 25."),
    (130, "cisco-fna", "cisco FNATIVE (IANA official)"),
    (131, "cisco-fna", "cisco FNATIVE (IANA official)"),
    (132, "cisco-sys", "cisco SYSMAINT (IANA official)"),
    (135, "Microsoft RPC EPMAP", "Microsoft Remote Procedure Call (RPC) Endpoint Mapper (EPMAP) service, for remote system access and management"),
    (137, "NetBIOS-ns", "NetBIOS Name Service, used for name registration and resolution"),
    (138, "NetBIOS-dgm", "NetBIOS Datagram Service, used for providing access to shared resources"),
    (139, "NetBIOS-ssn", "NetBIOS Session Service"),
    (143, "IMAP", "Internet Message Access Protocol (IMAP), management of electronic mail messages on a server"),
    (150, "sql-net", "SQL-NET (IANA official)"),
    (161, "SNMP-agents (unencrypted)", "Simple network management protocol; agents communicate on this port"),
    (162, "SNMP-trap (unencrypted)", "Simple network management protocol; listens for asynchronous traps"),
    (177, "XDMCP", "X Display Manager Control Protocol"),
    (179, "BGP", "Border Gateway Protocol"),
    (194, "IRC", "Internet Relay Chat"),
    (199, "SNPM", "Simple network management protocol"),
    (201, "AppleTalk", "AppleTalk Routing Maintenance. Trojan horses and computer viruses have used UDP port 201."),
    (264, "BGMP", "Border Gateway Multicast Protocol"),
    (318, "TSP", "Time Stamp Protocol"),
    (381, "HP Openview", "HP performance data collector"),
    (383, "HP Openview", "HP data alarm manager"),
    (389, "LDAP", "Lightweight directory access protocol"),
    (411, "(Multiple uses)", "Usually (but not guaranteed): Direct Connect Hub / Remote MT Protocol"),
    (412, "(Multiple uses)", "Usually (but not guaranteed): Direct Connect Client-to-Client / Trap Convention Port"),
    (427, "SLP", "Service Location Protocol"),
    (443, "HTTPS (HTTP over SSL)", "Hypertext Transfer Protocol Secure (HTTPS) uses TCP in versions 1.x and 2. HTTP/3 uses QUIC, a transport protocol on top of UDP."),
    (445, "Microsoft DS SMB", "Microsoft Directory Services: TCP for Active Directory, Windows shares; UDP for Server Message Block (SMB) file-sharing"),
    (464, "Kerberos", "For password settings on Kerberos"),
    (465, "SMTP over TLS/SSL, SSM", "Authenticated SMTP over TLS/SSL (SMTPS), URL Rendezvous Directory for Cisco's Source Specific Multicast protocol (SSM)"),
    (497, "Dantz Retrospect", "A software suite for backing up operating systems"),
    (500, "IPSec / ISAKMP / IKE", "Internet Protocol Security / Internet Security Association and Key Management Protocol / Internet Key Exchange"),
    (512, "rexec", "Remote Process Execution"),
    (513, "rlogin", "The Unix program rlogin allows users to log in on another host using a network."),
    (514, "syslog / rsync", "Syslog Protocol, for collecting and organizing all of the log files sent from the various devices on a network / The rsync file synchronization protocol efficiently transfers and synchronizes files between devices and networked computers."),
    (515, "LPD / LPR", "Line Printer Daemon protocol / Line Printer Remote protocol"),
    (520, "RIP", "Routing Information Protocol, used to find the optimal path between source and destination networks"),
    (521, "RIPng (IPv6)", "Routing Information Protocol next generation, the IPv6 compatible version of RIP"),
    (530, "RPC", "Remote Procedure Call"),
    (540, "UUCP", "Unix-to-Unix Copy Protocol"),
    (543, "Kerberos", "Kerberos authenticated rlogin"),
    (544, "Kerberos", "Kerberos authenticated remote shell"),
    (546, "DHCPv6", "Dynamic Host Configuration Protocol version 6. DHCPv6 Clients listen for DHCPv6 messages on UDP port 546."),
    (547, "DHCPv6", "DHCPv6 Servers and DHCPv6 Relay Agents listen for DHCPv6 messages on UDP port 547."),
    (548, "AFP", "Apple Filing Protocol"),
    (554, "RTSP", "Real Time Streaming Protocol"),
    (560, "rmonitor", "Remote Monitor"),
    (563, "NNTP over TLS/SSL", "Network News Transfer Protocol with encryption and verification"),
    (587, "SMTP", "For email message submission via SMTP"),
    (591, "FileMaker", "FileMaker Web Companion, the web publishing technology available in FileMaker versions 4-6"),
    (593, "Microsoft DCOM", "Distributed Component Object Model (DCOM)"),
    (596, "SMSD", "SysMan Station daemon"),
    (631, "IPP", "Internet Printing Protocol"),
    (636, "LDAP over TLS/SSL", "Lightweight Directory Access Protocol over TLS/SSL"),
    (639, "MSDP (PIM)", "Multicast Source Discovery Protocol, which is part of the Protocol Independent Multicast (PIM) family"),
    (646, "LDP (MPLS)", "Label Distribution Protocol, applies to routers capable of Multiprotocol Label Switching (MPLS)"),
    (691, "Microsoft Exchange", "Microsoft Exchange Routing"),
    (749, "Kerberos", "Kerberos admin (749 - 753 range)"),
    (750, "Kerberos", "Kerberos admin (749 - 753 range)"),
    (751, "Kerberos", "Kerberos admin (749 - 753 range)"),
    (752, "Kerberos", "Kerberos admin (749 - 753 range)"),
    (753, "Kerberos", "Kerberos admin (749 - 753 range)"),
    (754, "Kerberos prop", "Kerberos slave propagation"),
    (760, "Kerberos", "For password settings on Kerberos"),
    (853, "DNS (over TLS)", "Domain Name System name resolver over TLS"),
    (860, "iSCSI", "Internet Small Computer Systems Interface"),
    (873, "rsync", "The rsync file synchronization protocol efficiently transfers and synchronizes files between devices and networked computers."),
    (902, "VMware Server", "VMware ESXi, a hypervisor"),
    (944, "NFS", "Network file system"),
    (989, "FTPS", "File Transfer Protocol (data) over TLS/SSL"),
    (990, "FTPS", "File Transfer Protocol (control) over TLS/SSL"),
    (992, "Telnet (over TLS)", "Encrypted telnet"),
    (993, "IMAP over SSL (IMAPS)", "Internet Message Access Protocol over TLS/SSL"),
    (995, "POP3 over SSL (POP3S)", "Post Office Protocol 3 over TLS/SSL"),

    // Registered ports used by popular services: 1024 – 49151
    (1025, "Microsoft RPC / Teradata", "Microsoft Remote Procedure Call / Teradata db default port"),
    (1026, "Windows Messenger", "Windows Messenger popup spam"),
    (1027, "Windows Messenger", "Windows Messenger popup spam"),
    (1028, "Windows Messenger", "Windows Messenger popup spam"),
    (1029, "Windows Messenger", "Windows Messenger popup spam"),
    (1080, "SOCKS proxy / MyDoom", "(SOCKS proxy) SOCKS stands for Socket Secure. This protocol exchanges network packets between a client and server through a proxy server. / (My Doom) Possibly computer virus"),
    (1194, "OpenVPN", "OpenVPN"),
    (1214, "KAZAA", "A peer-to-peer file-sharing protocol"),
    (1241, "Nessus", "Nessus Security Scanner"),
    (1311, "Dell OpenManage", "Dell EMC OpenManage Server Administrator Web GUI"),
    (1337, "WASTE", "WASTE peer-to-peer encrypted file-sharing Program"),
    (1433, "MSSQL", "Microsoft SQL Server default port"),
    (1434, "MSSQL", "Microsoft SQL Server default port"),
    (1521, "Oracle Net Listener", "Allows Oracle client connections to the database by using Oracle Net Services. You can configure this port during installation. To reconfigure this port, use NETCA."),
    (1583, "Pervasive SQL", "Parvasive SQL default port"),
    (1589, "Cisco VQP", "Cisco VLAN Query Protocol (VQP)"),
    (1630, "Oracle Connection Manager", "Listening port for Oracle client connections to Oracle Connection Manager. You can configure Oracle Connection Manager after installation using NETCA."),
    (1701, "L2TP VPN", "Layer Two Tunneling Protocol Virtual Private Networking"),
    (1720, "H.323", "H.323 Call Control Signaling, a VoIP call control protocol"),
    (1723, "Microsoft PPTP", "Point-to-Point Tunneling Protocol Virtual Private Networking"),
    (1725, "Steam", "Valve Steam Client uses port 1725"),
    (1741, "CiscoWorks SNMS 2000", "CiscoWorks Small Network Management Solution web server"),
    (1755, "MMS", "Microsoft Media Server"),
    (1812, "RADIUS", "RADIUS server authentication and authorization"),
    (1813, "RADIUS", "RADIUS server accounting"),
    (1830, "Oracle Net8 CMan Admin", "Oracle Net8 CMan Admin default port"),
    (1832, "Oracle Net8 CMan Admin", "Oracle Enterprise Management Agent HTTP default port"),
    (1863, "(Multiple uses)", "Usually (but not guaranteed): UMSN Messenger / Xbox Live 360"),
    (1900, "UPnP", "Universal Plug and Play"),
    (1985, "Cisco HSRP", "Hot Standby Router Protocol"),
    (2000, "Cisco SCCP", "Skinny Client Control Protocol"),
    (2002, "Cisco ACS", "Access Control Server"),
    (2049, "NFS", "Network File Sharing"),
    (2082, "cPanel", "cPanel default"),
    (2083, "radsec / cPanel", "Secure RADIUS Service (radsec) / cPanel default SSL"),
    (2100, "amiganetfs", "Amiga Network Filesystem"),
    (2105, "Kerberos login", "Kerberos auth and encrypted rlogin"),
    (2181, "ZooKeeper", "ZooKeeper is a high-performance coordination service for distributed applications. It exposes common services - such as naming, configuration management, synchronization, and group services - in a simple interface so you don't have to write them from scratch. You can use it off-the-shelf to implement consensus, group management, leader election, and presence protocols. And you can build on it for your own, specific needs."),
    (2222, "DirectAdmin", "Graphical web hosting control panel"),
    (2302, "HALO Game", "The game HALO uses this port extensively"),
    (2379, "etcd", "Distributed reliable key-value store for the most critical data of a distributed system"),
    (2380, "etcd", "Distributed reliable key-value store for the most critical data of a distributed system"),
    (2483, "Oracle", "Oracle database listening for insecure client connections to the listener, replaces port 1521"),
    (2484, "Oracle", "Oracle database listening for SSL client connections to the listener"),
    (2601, "Zebra vty", "zebra vty ; IANA registered for: discp client ; Sometimes this port is used by malware"),
    (2888, "ZooKeeper", "ZooKeeper is a high-performance coordination service for distributed applications. It exposes common services - such as naming, configuration management, synchronization, and group services - in a simple interface so you don't have to write them from scratch. You can use it off-the-shelf to implement consensus, group management, leader election, and presence protocols. And you can build on it for your own, specific needs."),
    (2967, "Symantec AV", "Symantec System Center agent (SSC-AGENT)"),
    (3000, "Frontend default port", "Usually port for frontend applications in development mode"),
    (3050, "Interbase DB / Firebird", "Borland Interbase database / Firebird is an open-source SQL relational database management system"),
    (3051, "Pervasive SQL", "Parvasive SQL default port"),
    (3128, "HTTP Proxy", "Common web proxy server ports: 80, 8080, 3128, 6588"),
    (3222, "GLBP", "Gateway Load Balancing Protocol"),
    (3260, "iSCSI Target", "Microsoft iSCSI Target Server"),
    (3306, "MySQL / Maria DB", "MySQL database system / Maria DB (fork of MySQL, that's why it's on the same port)"),
    (3307, "MySQL / Maria DB", "MySQL database system / Maria DB (fork of MySQL, that's why it's on the same port). The port 3307 is usually used by wamp as a secondary db."),
    (3389, "RDP", "Windows Remote Desktop Protocol (Microsoft Terminal Server)"),
    (3528, "jacorb", "CORBA services for JTS transactions and other ORB-dependent services"),
    (3529, "jacorb-ssl", "SSL-encrypted CORBA services"),
    (3689, "DAAP", "Digital Audio Access Protocol, used by Apple's iTunes and AirPort Express"),
    (3690, "SVN", "Apache Subversion, a version control system"),
    (3724, "Blizzard Games", "Some Blizzard games, Unofficial Club Penguin Disney online game for kids"),
    (3784, "Ventrilo VoIP", "Ventrilo's Voice over Internet Protocol program"),
    (3785, "Ventrilo VoIP", "Ventrilo's Voice over Internet Protocol program"),
    (3888, "ZooKeeper", "ZooKeeper is a high-performance coordination service for distributed applications. It exposes common services - such as naming, configuration management, synchronization, and group services - in a simple interface so you don't have to write them from scratch. You can use it off-the-shelf to implement consensus, group management, leader election, and presence protocols. And you can build on it for your own, specific needs."),
    (4333, "mSQL", "Mini SQL server"),
    (4444, "Kerberos / Blaster", "Kerberos 5 to 4 ticket translator / Possibly computer worm"),
    (4447, "JBoss remoting", "Used for remote EJB invocation"),
    (4500, "IPSec NAT Traversal", "Internet Protocol Security Network Address Translation (NAT) Traversal"),
    (4664, "Google Desktop", "Google Desktop's built-in HTTP server and indexing software"),
    (4672, "eMule", "Peer-to-peer file-sharing software"),
    (4712, "JBoss txn-recovery-environment", "The JTA transaction recovery manager"),
    (4713, "Jboss txn-status-manager", "The JTA / JTS transation manager"),
    (4899, "Radmin", "Remote computer control software"),
    (5000, "UPnP", "Universal Plug and Play"),
    (5001, "iperf", "Tool for measuring TCP and UDP bandwidth performance"),
    (5004, "RTP / RTSP", "Real-time Transport Protocol, Real Time Streaming Protocol"),
    (5005, "RTP / RTSP", "Real-time Transport Protocol, Real Time Streaming Protocol"),
    (5050, "Yahoo! Messenger / Mesos", "Instant messaging service from Yahoo / Apache Mesos abstracts CPU, memory, storage, and other compute resources away from machines (physical or virtual), enabling fault-tolerant and elastic distributed systems to easily be built and run effectively."),
    (5051, "Mesos", "Apache Mesos abstracts CPU, memory, storage, and other compute resources away from machines (physical or virtual), enabling fault-tolerant and elastic distributed systems to easily be built and run effectively."),
    (5060, "SIP", "Session Initiation Protocol"),
    (5061, "SIP-TLS", "Session Initiation Protocol over TLS"),
    (5190, "(Multiple uses)", "Usually (but not guaranteed): ICQ / AIM (AOL Instant Messenger) / Apple iChat"),
    (5222, "XMPP", "Extensible Messaging and Presence Protocol Client Connection; also used in Google Talk, Jabber, Apple iChat, WhatsApp, etc."),
    (5223, "XMPP", "Extensible Messaging and Presence Protocol Client Connection; also used in Google Talk, Jabber, Apple iChat, WhatsApp, etc."),
    (5353, "MDNS", "Multicast DNS"),
    (5432, "PostgreSQL", "PostgreSQL database system"),
    (5445, "JMS messaging", "JMS service"),
    (5455, "JMS messaging-throughput", "Used by JMS Remoting"),
    (5631, "pcAnywhere", "Symantec pcAnywhere"),
    (5632, "pcAnywhere", "Symantec pcAnywhere"),
    (5800, "VNC over HTTP", "Virtual Network Computing (VNC)"),
    (5900, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"), 
    (5901, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5902, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5903, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5904, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5905, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5906, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5907, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5908, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5909, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5910, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5911, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5912, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5913, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5914, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5915, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5916, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5917, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5918, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5919, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5920, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5921, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5922, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5923, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5924, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5925, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5926, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5927, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5928, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5929, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5930, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5931, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5932, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5933, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5934, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5935, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5936, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5937, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5938, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5939, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5940, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5941, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5942, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5943, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5944, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5945, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5946, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5947, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5948, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5949, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5950, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5951, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5952, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5953, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5954, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5955, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5956, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5957, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5958, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5959, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5960, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5961, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5962, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5963, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5964, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5965, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5966, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5967, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5968, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5969, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5970, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5971, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5972, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5973, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5974, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5975, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5976, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5977, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5978, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5979, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5980, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5981, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5982, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5983, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5984, "RFB / VNC Server / CouchDB", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range) / CouchDB default port"),
    (5985, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5986, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5987, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5988, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5989, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5990, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5991, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5992, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5993, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5994, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5995, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5996, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5997, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5998, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5999, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (6000, "X11", "X Window System protocol for delivering payloads between X clients and servers"),
    (6001, "X11", "X Window System protocol for delivering payloads between X clients and servers"),
    (6129, "DameWare", "Remote access software developed by SolarWinds"),
    (6257, "WinMX", "Windows Music Exchange, peer-to-peer file-sharing freeware"),
    (6346, "Gnutella2", "Peer-to-peer network protocol"),
    (6347, "Gnutella2", "Peer-to-peer network protocol"),
    (6379, "Redis", "Popular non-relational database management system (NoSql)"),
    (6443, "Kubernetes", "Kubernetes API"),
    (6566, "SANE", "Scanner Access Now Easy"),
    (6588, "AnalogX / HTTP Proxy", "AnalogX proxy server / Common web proxy server ports: 80, 8080, 3128, 6588"),
    (6665, "IRC", "Internet Relay Chat (6665 - 6669 range)"),
    (6666, "IRC", "Internet Relay Chat (6665 - 6669 range)"),
    (6667, "IRC", "Internet Relay Chat (6665 - 6669 range)"),
    (6668, "IRC", "Internet Relay Chat (6665 - 6669 range)"),
    (6669, "IRC", "Internet Relay Chat (6665 - 6669 range)"),
    (6679, "IRC over SSL", "Internet Relay Chat"),
    (6697, "IRC over SSL", "Internet Relay Chat"),
    (6699, "Napster", "Peer-to-peer file-sharing application"),
    (6881, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6891, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6892, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6893, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6894, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6895, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6896, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6897, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6898, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6899, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6900, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6901, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6970, "Quicktime / BitTorrent", "QuickTime streaming server / Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6999, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (7000, "Cassandra", "Inter-node communication within the cluster on Apache Cassandra"),
    (7001, "Cassandra", "SSL-enabled inter-node communication within the cluster on Apache Cassandra"),
    (7210, "MaxDB", "MaxDB default port"),
    (7199, "Cassandra JMX", "Java Management Extensions on Apache Cassandra"),
    (7473, "Neo4j", "Neo4j db default port"),
    (7474, "Neo4j", "Neo4j db default port"),
    (7500, "jgroups-diagnostics", "Multicast. Used for peer discovery in HA clusters"),
    (7600, "jgroups-tcp", "Unicast peer discovery in HA clusters using TCP"),
    (7574, "Solr", "Solr db default port"),
    (7687, "Neo4j", "Neo4j db default port"),
    (8000, "Internet Radio / Django default port", "Commonly choice of alternate HTTP port for web applications / Usually django apps run on this port"),
    (8005, "Tomcat", "Commont Tomcat web server port"),
    (8009, "AJP / Tomcat", "Apache JServ Protocol. Used for HTTP clustering and load balancing / Commont Tomcat web server port"),
    (8080, "HTTP Proxy", "Common web proxy server ports: 80, 8080, 3128, 6588"),
    (8086, "Kaspersky AV", "Kaspersky AV Control Center"),
    (8087, "Kaspersky AV / Riak", "Kaspersky AV Control Center / RiakDB default port"),
    (8090, "JBoss osgi-http", "Used by internal components which use the OSGi subsystem"),
    (8098, "Riak", "RiakDB default port"),
    (8091, "Couchbase", "Couchbase database server default port"),
    (8118, "Privoxy", "Advertisement-filtering Web proxy"),
    (8200, "VMware Server", "VMware vSphere Fault Tolerance"),
    (8222, "VMware Server", "VMware Server Management User Interface (insecure Web interface)."),
    (8300, "Hashicorp consul", "HashiCorp Consul is a service networking solution that enables teams to manage secure network connectivity between services and across on-prem and multi-cloud environments and runtimes. Consul offers service discovery, service mesh, traffic management, and automated updates to network infrastructure device"),
    (8301, "Hashicorp consul", "HashiCorp Consul is a service networking solution that enables teams to manage secure network connectivity between services and across on-prem and multi-cloud environments and runtimes. Consul offers service discovery, service mesh, traffic management, and automated updates to network infrastructure device"),
    (8302, "Hashicorp consul", "HashiCorp Consul is a service networking solution that enables teams to manage secure network connectivity between services and across on-prem and multi-cloud environments and runtimes. Consul offers service discovery, service mesh, traffic management, and automated updates to network infrastructure device"),
    (8400, "Hashicorp consul", "HashiCorp Consul is a service networking solution that enables teams to manage secure network connectivity between services and across on-prem and multi-cloud environments and runtimes. Consul offers service discovery, service mesh, traffic management, and automated updates to network infrastructure device"),
    (8443, "Secondary https", "SSL-encrypted connection between deployed web applications and clients"),
    (8500, "(Multiple uses)", "Usually (but not guaranteed): Adobe ColdFusion / Flight Message Transfer Protocol / Hashicorp consul"),
    (8529, "ArangoDB", "ArangoDB default port"),
    (8600, "Hashicorp consul", "HashiCorp Consul is a service networking solution that enables teams to manage secure network connectivity between services and across on-prem and multi-cloud environments and runtimes. Consul offers service discovery, service mesh, traffic management, and automated updates to network infrastructure device"),
    (8983, "Solr", "Solr db default port"),
    (9042, "Cassandra", "Apache Cassandra, a NoSql database"),
    (9100, "PDL", "PDL Data Stream, used for printing to certain network printers"),
    (9101, "Bacula", "For automating backup tasks"),
    (9102, "Bacula", "For automating backup tasks"),
    (9103, "Bacula", "For automating backup tasks"),
    (9119, "MXit", "MXit Instant Messaging (deprecated)"),
    (9200, "Elasticsearch", "Elasticsearch database default port"),
    (9300, "Elasticsearch", "Elasticsearch database default port"),
    (9800, "WebDAV", "Web-based Distributed Authoring and Versioning, an extension of HTTP"),
    (9990, "JBoss / WildFly", "The Web Management Console port / WildFly Elytron Security console port"),
    (9993, "WildFly server console", "WildFly Elytron Security console port"),
    (9999, "Urchin / JBoss", "Urchin Web Analytics / The port used by the JBoss Management Console and Management API"),
    (10000, "(Multiple uses)", "Usually (but not guaranteed Network Data Management Protocol / applications): Webmin / BackupExec / Viatalk ; gaming: The Matrix Online, Dungeon Fighter"),
    (10113, "NetIQ", "NetIQ Endpoint"),
    (10114, "NetIQ", "NetIQ Qcheck"),
    (10115, "NetIQ", "NetIQ Endpoint"),
    (10116, "NetIQ", "NetIQ VoIP Assessor"),
    (10161, "SNMP-agents (encrypted)", "Simple network management protocol; agents communicate on this port"),
    (10162, "SNMP-trap (encrypted)", "Simple network management protocol; listens for asynchronous traps"),
    (11371, "OpenPGP", "OpenPGP HTTP Keyserver"),
    (12345, "NetBus", "Possibly NetBus remote administration tool (usage could be legit, or possibly as a Trojan horse)"),
    (13720, "NetBackup", "NetBackup request daemon"),
    (13721, "NetBackup", "NetBackup request daemon"),
    (15118, "Dipnet / Oddbob", "Possibly a trojan horse"),
    (19226, "AdminSecure", "Panda Software AdminSecure Communication Agent"),
    (19638, "Ensim", "Ensim Control Panel"),
    (20000, "Usermin", "Web email interface for regular non-root users"),
    (23364, "JBoss mod_cluster", "Multicast port for communication between JBoss EAP 6 and the HTTP load balancer"),
    (24800, "Synergy", "Keyboard/mouse sharing software"),
    (25999, "Xfire", "Communication tool for gamers (deprecated)"),
    (27017, "MongoDB", "NoSql database"),
    (27018, "MongoDB", "NoSql database"),
    (27019, "MongoDB", "NoSql database"),
    (27374, "Sub7", "Possibly a trojan horse"),
    (28015, "RethinkDB", "Rethink database default port"),
    (28017, "MongoDB", "NoSql database"),
    (29015, "RethinkDB", "Rethink database default port"),
    (31337, "Back Orifice", "Possibly remote administration tool (usage could be legit, or possibly as a Trojan horses)"),
    (39013, "SAP HANA", "SAP HANA db default port"),
    (45700, "jgroups-mping", "Multicast. Used to discover initial membership in a HA cluster."),
    (45688, "jgroups-udp", "Unicast peer discovery in HA clusters using UDP"),
    
    // Dynamic private ports: 49152 - 65535
    (49896, "Oracle Clusterware", "CRS daemon default port"),
    (50000, "IBM Db2", "IBM Db2 default port"),
    (54200, "jgroups-udp-fd", "Used for HA failure detection over UDP"),
    (55200, "jgroups-udp", "Unicast peer discovery in HA clusters using UDP"),
    (57600, "jgroups-tcp-fd", "Used for HA failure detection over TCP"),
];

// TODO: Add more commands (like http request and such)
pub const PORT_FUZZING_COMMANDS: [&[u8]; 3] = [b"info\n", b"help\n", b"version\n"];
