use super::ip::Port;

// I want the window smaller for debugging
#[cfg(debug_assertions)]
pub const WORKSPACE_WINDOW_WIDTH: f32 = 880.0;
#[cfg(debug_assertions)]
pub const WORKSPACE_WINDOW_HEIGHT: f32 = 1080.0;

#[cfg(not(debug_assertions))]
pub const WORKSPACE_WINDOW_WIDTH: f32 = 1450.0;
#[cfg(not(debug_assertions))]
pub const WORKSPACE_WINDOW_HEIGHT: f32 = 1080.0;

pub const DEFAULT_WINDOW_STARTING_POS: eframe::epaint::Pos2 = eframe::epaint::Pos2 {
    x: WORKSPACE_WINDOW_WIDTH / 2.0 - 150.0,
    y: WORKSPACE_WINDOW_HEIGHT / 2.0 - 150.0,
};

#[cfg(windows)]
pub const LINE_ENDING: &str = "\r\n";
#[cfg(not(windows))]
pub const LINE_ENDING: &str = "\n";

pub const DEFAULT_SPACER: f32 = 5.0;
pub const ACTION_SPACER: f32 = 10.0;

pub const TRASH_ICON: &str = "🗑";

pub const MOST_COMMON_PORTS: [Port; 4] = [21, 22, 80, 443]; //TODO

// Fill with data from https://docs.oracle.com/en/database/oracle/oracle-database/18/rilin/port-numbers-and-protocols-of-oracle-components.html#GUID-D168F70C-BECE-4F9A-B616-D9103A35F1FF
pub const ALL_COMMON_PORTS_LENGHT: usize = 500;
// Port , Protocol , Usefull info
pub const ALL_COMMON_PORTS: [(Port, &str, &str); ALL_COMMON_PORTS_LENGHT] = [
    // Well-known/System ports: 0 – 1023
    (7, "Echo", "Echo service"),
    (19, "CHARGEN", "Character Generator Protocol, has severe vulnerabilities and thus is rarely used nowadays"),
    (20, "FTP-data", "File Transfer Protocol data transfer"),
    (21, "FTP", "File Transfer Protocol command control"),
    (22, "SSH/SCP/SFTP", "Secure Shell, secure logins, file transfers (scp, sftp), and port forwarding"),
    (23, "Telnet", "Telnet protocol, for unencrypted text communications"),
    (25, "SMTP", "Simple Mail Transfer Protocol, used for email routing between mail servers"),
    (42, "WINS Replication", "Microsoft Windows Internet Name Service, vulnerable to attacks on a local network"),
    (43, "WHOIS", "Whois service, provides domain-level information"),
    (49, "TACACS", "Terminal Access Controller Access-Control System, provides remote authentication and related services for network access"),
    (53, "DNS", "Domain Name System name resolver"),
    (67, "DHCP/BOOTP", "Dynamic Host Configuration Protocol and its predecessor Bootstrap Protocol Server; server port"),
    (68, "DHCP/BOOTP", "Dynamic Host Configuration Protocol and its predecessor Bootstrap Protocol Server; client port"),
    (69, "TFTP", "Trivial File Transfer Protocol"),
    (70, "Gopher", "Gopher is a communication protocol for distributing, searching, and retrieving documents in Internet Protocol (IP) networks"),
    (79, "Finger", "Name/Finger protocol and Finger user information protocol, for retrieving and manipulating user information"),
    (80, "HTTP", "Hypertext Transfer Protocol (HTTP) uses TCP in versions 1.x and 2. HTTP/3 uses QUIC, a transport protocol on top of UDP"),
    (88, "Kerberos", "Network authentication system"),
    (102, "Microsoft Exchange ISO-TSAP", "Microsoft Exchange ISO Transport Service Access Point (TSAP) Class 0 protocol"),
    (110, "POP3", "Post Office Protocol, version 3 (POP3)"),
    (113, "Ident", "Identification Protocol, for identifying the user of a particular TCP connection"),
    (119, "NNTP (Usenet)", "Network News Transfer Protocol"),
    (123, "NTP", "Network Time Protocol"),
    (135, "Microsoft RPC EPMAP", "Microsoft Remote Procedure Call (RPC) Endpoint Mapper (EPMAP) service, for remote system access and management"),
    (137, "NetBIOS-ns", "NetBIOS Name Service, used for name registration and resolution"),
    (138, "NetBIOS-dgm", "NetBIOS Datagram Service, used for providing access to shared resources"),
    (139, "NetBIOS-ssn", "NetBIOS Session Service"),
    (143, "IMAP", "Internet Message Access Protocol (IMAP), management of electronic mail messages on a server"),
    (161, "SNMP-agents (unencrypted)", "Simple network management protocol; agents communicate on this port"),
    (162, "SNMP-trap (unencrypted)", "Simple network management protocol; listens for asynchronous traps"),
    (177, "XDMCP", "X Display Manager Control Protocol"),
    (179, "BGP", "Border Gateway Protocol"),
    (194, "IRC", "Internet Relay Chat"),
    (199, "SNPM", "Simple network management protocol"),
    (201, "AppleTalk", "AppleTalk Routing Maintenance. Trojan horses and computer viruses have used UDP port 201."),
    (264, "BGMP", "Border Gateway Multicast Protocol"),
    (318, "TSP", "Time Stamp Protocol"),
    (381, "HP Openview", "HP performance data collector"),
    (383, "HP Openview", "HP data alarm manager"),
    (389, "LDAP", "Lightweight directory access protocol"),
    (411, "(Multiple uses)", "Usually (but not guaranteed): Direct Connect Hub / Remote MT Protocol"),
    (412, "(Multiple uses)", "Usually (but not guaranteed): Direct Connect Client-to-Client / Trap Convention Port"),
    (427, "SLP", "Service Location Protocol"),
    (443, "HTTPS (HTTP over SSL)", "Hypertext Transfer Protocol Secure (HTTPS) uses TCP in versions 1.x and 2. HTTP/3 uses QUIC, a transport protocol on top of UDP."),
    (445, "Microsoft DS SMB", "Microsoft Directory Services: TCP for Active Directory, Windows shares; UDP for Server Message Block (SMB) file-sharing"),
    (464, "Kerberos", "For password settings on Kerberos"),
    (465, "SMTP over TLS/SSL, SSM", "Authenticated SMTP over TLS/SSL (SMTPS), URL Rendezvous Directory for Cisco's Source Specific Multicast protocol (SSM)"),
    (497, "Dantz Retrospect", "A software suite for backing up operating systems"),
    (500, "IPSec / ISAKMP / IKE", "Internet Protocol Security / Internet Security Association and Key Management Protocol / Internet Key Exchange"),
    (512, "rexec", "Remote Process Execution"),
    (513, "rlogin", "The Unix program rlogin allows users to log in on another host using a network."),
    (514, "syslog / rsync", "Syslog Protocol, for collecting and organizing all of the log files sent from the various devices on a network / The rsync file synchronization protocol efficiently transfers and synchronizes files between devices and networked computers."),
    (515, "LPD / LPR", "Line Printer Daemon protocol / Line Printer Remote protocol"),
    (520, "RIP", "Routing Information Protocol, used to find the optimal path between source and destination networks"),
    (521, "RIPng (IPv6)", "Routing Information Protocol next generation, the IPv6 compatible version of RIP"),
    (530, "RPC", "Remote Procedure Call"),
    (540, "UUCP", "Unix-to-Unix Copy Protocol"),
    (543, "Kerberos", "Kerberos authenticated rlogin"),
    (544, "Kerberos", "Kerberos authenticated remote shell"),
    (546, "DHCPv6", "Dynamic Host Configuration Protocol version 6. DHCPv6 Clients listen for DHCPv6 messages on UDP port 546."),
    (547, "DHCPv6", "DHCPv6 Servers and DHCPv6 Relay Agents listen for DHCPv6 messages on UDP port 547."),
    (548, "AFP", "Apple Filing Protocol"),
    (554, "RTSP", "Real Time Streaming Protocol"),
    (560, "rmonitor", "Remote Monitor"),
    (563, "NNTP over TLS/SSL", "Network News Transfer Protocol with encryption and verification"),
    (587, "SMTP", "For email message submission via SMTP"),
    (591, "FileMaker", "FileMaker Web Companion, the web publishing technology available in FileMaker versions 4-6"),
    (593, "Microsoft DCOM", "Distributed Component Object Model (DCOM)"),
    (596, "SMSD", "SysMan Station daemon"),
    (631, "IPP", "Internet Printing Protocol"),
    (636, "LDAP over TLS/SSL", "Lightweight Directory Access Protocol over TLS/SSL"),
    (639, "MSDP (PIM)", "Multicast Source Discovery Protocol, which is part of the Protocol Independent Multicast (PIM) family"),
    (646, "LDP (MPLS)", "Label Distribution Protocol, applies to routers capable of Multiprotocol Label Switching (MPLS)"),
    (691, "Microsoft Exchange", "Microsoft Exchange Routing"),
    (749, "Kerberos", "Kerberos admin (749 - 753 range)"),
    (750, "Kerberos", "Kerberos admin (749 - 753 range)"),
    (751, "Kerberos", "Kerberos admin (749 - 753 range)"),
    (752, "Kerberos", "Kerberos admin (749 - 753 range)"),
    (753, "Kerberos", "Kerberos admin (749 - 753 range)"),
    (754, "Kerberos prop", "Kerberos slave propagation"),
    (760, "Kerberos", "For password settings on Kerberos"),
    (853, "DNS (over TLS)", "Domain Name System name resolver over TLS"),
    (860, "iSCSI", "Internet Small Computer Systems Interface"),
    (873, "rsync", "The rsync file synchronization protocol efficiently transfers and synchronizes files between devices and networked computers."),
    (902, "VMware Server", "VMware ESXi, a hypervisor"),
    (944, "NFS", "Network file system"),
    (989, "FTPS", "File Transfer Protocol (data) over TLS/SSL"),
    (990, "FTPS", "File Transfer Protocol (control) over TLS/SSL"),
    (992, "Telnet (over TLS)", "Encrypted telnet"),
    (993, "IMAP over SSL (IMAPS)", "Internet Message Access Protocol over TLS/SSL"),
    (995, "POP3 over SSL (POP3S)", "Post Office Protocol 3 over TLS/SSL"),

    // Registered ports used by popular services: 1024 – 49151
    (1025, "Microsoft RPC / Teradata", "Microsoft Remote Procedure Call / Teradata db default port"),
    (1026, "Windows Messenger", "Windows Messenger popup spam"),
    (1027, "Windows Messenger", "Windows Messenger popup spam"),
    (1028, "Windows Messenger", "Windows Messenger popup spam"),
    (1029, "Windows Messenger", "Windows Messenger popup spam"),
    (1080, "SOCKS proxy / MyDoom", "(SOCKS proxy) SOCKS stands for Socket Secure. This protocol exchanges network packets between a client and server through a proxy server. / (My Doom) Possibly computer virus"),
    (1194, "OpenVPN", "OpenVPN"),
    (1214, "KAZAA", "A peer-to-peer file-sharing protocol"),
    (1241, "Nessus", "Nessus Security Scanner"),
    (1311, "Dell OpenManage", "Dell EMC OpenManage Server Administrator Web GUI"),
    (1337, "WASTE", "WASTE peer-to-peer encrypted file-sharing Program"),
    (1433, "MSSQL", "Microsoft SQL Server default port"),
    (1434, "MSSQL", "Microsoft SQL Server default port"),
    (1521, "Oracle Net Listener", "Allows Oracle client connections to the database by using Oracle Net Services. You can configure this port during installation. To reconfigure this port, use NETCA."),
    (1589, "Cisco VQP", "Cisco VLAN Query Protocol (VQP)"),
    (1630, "Oracle Connection Manager", "Listening port for Oracle client connections to Oracle Connection Manager. You can configure Oracle Connection Manager after installation using NETCA."),
    (1701, "L2TP VPN", "Layer Two Tunneling Protocol Virtual Private Networking"),
    (1720, "H.323", "H.323 Call Control Signaling, a VoIP call control protocol"),
    (1723, "Microsoft PPTP", "Point-to-Point Tunneling Protocol Virtual Private Networking"),
    (1725, "Steam", "Valve Steam Client uses port 1725"),
    (1741, "CiscoWorks SNMS 2000", "CiscoWorks Small Network Management Solution web server"),
    (1755, "MMS", "Microsoft Media Server"),
    (1812, "RADIUS", "RADIUS server authentication and authorization"),
    (1813, "RADIUS", "RADIUS server accounting"),
    (1830, "Oracle Net8 CMan Admin", "Oracle Net8 CMan Admin default port"),
    (1832, "Oracle Net8 CMan Admin", "Oracle Enterprise Management Agent HTTP default port"),
    (1863, "(Multiple uses)", "Usually (but not guaranteed): UMSN Messenger / Xbox Live 360"),
    (1900, "UPnP", "Universal Plug and Play"),
    (1985, "Cisco HSRP", "Hot Standby Router Protocol"),
    (2000, "Cisco SCCP", "Skinny Client Control Protocol"),
    (2002, "Cisco ACS", "Access Control Server"),
    (2049, "NFS", "Network File Sharing"),
    (2082, "cPanel", "cPanel default"),
    (2083, "radsec / cPanel", "Secure RADIUS Service (radsec) / cPanel default SSL"),
    (2100, "amiganetfs", "Amiga Network Filesystem"),
    (2105, "Kerberos login", "Kerberos auth and encrypted rlogin"),
    (2222, "DirectAdmin", "Graphical web hosting control panel"),
    (2302, "HALO Game", "The game HALO uses this port extensively"),
    (2483, "Oracle", "Oracle database listening for insecure client connections to the listener, replaces port 1521"),
    (2484, "Oracle", "Oracle database listening for SSL client connections to the listener"),
    (2601, "Zebra vty", "zebra vty ; IANA registered for: discp client ; Sometimes this port is used by malware"),
    (2745, "Bagle.C - Bagle.H", "Possible computer worms"),
    (2967, "Symantec AV", "Symantec System Center agent (SSC-AGENT)"),
    (3050, "Interbase DB", "Borland Interbase database"),
    (3074, "XBOX Live", "Gaming: Xbox LIVE and Games for Windows - Live"),
    (3127, "MyDoom", "Possibly computer worm"),
    (3128, "HTTP Proxy", "Common web proxy server ports: 80, 8080, 3128, 6588"),
    (3222, "GLBP", "Gateway Load Balancing Protocol"),
    (3260, "iSCSI Target", "Microsoft iSCSI Target Server"),
    (3306, "MySQL / Maria DB", "MySQL database system / Maria DB (fork of MySQL, that's why it's on the same port)"),
    (3307, "MySQL / Maria DB", "MySQL database system / Maria DB (fork of MySQL, that's why it's on the same port). The port 3307 is usually used by wamp as a secondary db."),
    (3389, "RDP", "Windows Remote Desktop Protocol (Microsoft Terminal Server)"),
    (3689, "DAAP", "Digital Audio Access Protocol, used by Apple's iTunes and AirPort Express"),
    (3690, "SVN", "Apache Subversion, a version control system"),
    (3724, "Blizzard Games", "Some Blizzard games, Unofficial Club Penguin Disney online game for kids"),
    (3784, "Ventrilo VoIP", "Ventrilo's Voice over Internet Protocol program"),
    (3785, "Ventrilo VoIP", "Ventrilo's Voice over Internet Protocol program"),
    (4333, "mSQL", "Mini SQL server"),
    (4444, "Kerberos / Blaster", "Kerberos 5 to 4 ticket translator / Possibly computer worm"),
    (4500, "IPSec NAT Traversal", "Internet Protocol Security Network Address Translation (NAT) Traversal"),
    (4664, "Google Desktop", "Google Desktop's built-in HTTP server and indexing software"),
    (4672, "eMule", "Peer-to-peer file-sharing software"),
    (4899, "Radmin", "Remote computer control software"),
    (5000, "UPnP", "Universal Plug and Play"),
    (5001, "iperf", "Tool for measuring TCP and UDP bandwidth performance"),
    (5004, "RTP / RTSP", "Real-time Transport Protocol, Real Time Streaming Protocol"),
    (5005, "RTP / RTSP", "Real-time Transport Protocol, Real Time Streaming Protocol"),
    (5050, "Yahoo! Messenger", "Instant messaging service from Yahoo"),
    (5060, "SIP", "Session Initiation Protocol"),
    (5061, "SIP-TLS", "Session Initiation Protocol over TLS"),
    (5190, "(Multiple uses)", "Usually (but not guaranteed): ICQ / AIM (AOL Instant Messenger) / Apple iChat"),
    (5222, "XMPP", "Extensible Messaging and Presence Protocol Client Connection; also used in Google Talk, Jabber, Apple iChat, WhatsApp, etc."),
    (5223, "XMPP", "Extensible Messaging and Presence Protocol Client Connection; also used in Google Talk, Jabber, Apple iChat, WhatsApp, etc."),
    (5353, "MDNS", "Multicast DNS"),
    (5432, "PostgreSQL", "PostgreSQL database system"),
    (5554, "Sasser", "Possibly computer worm"),
    (5631, "pcAnywhere", "Symantec pcAnywhere"),
    (5632, "pcAnywhere", "Symantec pcAnywhere"),
    (5800, "VNC over HTTP", "Virtual Network Computing (VNC)"),
    (5900, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"), 
    (5901, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5902, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5903, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5904, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5905, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5906, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5907, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5908, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5909, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5910, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5911, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5912, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5913, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5914, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5915, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5916, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5917, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5918, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5919, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5920, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5921, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5922, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5923, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5924, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5925, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5926, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5927, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5928, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5929, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5930, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5931, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5932, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5933, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5934, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5935, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5936, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5937, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5938, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5939, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5940, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5941, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5942, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5943, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5944, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5945, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5946, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5947, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5948, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5949, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5950, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5951, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5952, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5953, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5954, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5955, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5956, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5957, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5958, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5959, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5960, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5961, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5962, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5963, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5964, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5965, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5966, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5967, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5968, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5969, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5970, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5971, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5972, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5973, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5974, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5975, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5976, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5977, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5978, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5979, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5980, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5981, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5982, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5983, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5984, "RFB / VNC Server / CouchDB", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range) / CouchDB default port"),
    (5985, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5986, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5987, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5988, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5989, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5990, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5991, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5992, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5993, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5994, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5995, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5996, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5997, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5998, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (5999, "RFB / VNC Server", "VNC Remote Frame Buffer RFB protocol (5900 - 5999 range)"),
    (6000, "X11", "X Window System protocol for delivering payloads between X clients and servers"),
    (6001, "X11", "X Window System protocol for delivering payloads between X clients and servers"),
    (6112, "Diablo Game", "Gaming"),
    (6129, "DameWare", "Remote access software developed by SolarWinds"),
    (6257, "WinMX", "Windows Music Exchange, peer-to-peer file-sharing freeware"),
    (6346, "Gnutella2", "Peer-to-peer network protocol"),
    (6347, "Gnutella2", "Peer-to-peer network protocol"),
    (6379, "Redis", "Popular non-relational database management system (NoSql)"),
    (6500, "GameSpy", "Gaming"),
    (6566, "SANE", "Scanner Access Now Easy"),
    (6588, "AnalogX / HTTP Proxy", "AnalogX proxy server / Common web proxy server ports: 80, 8080, 3128, 6588"),
    (6665, "IRC", "Internet Relay Chat (6665 - 6669 range)"),
    (6666, "IRC", "Internet Relay Chat (6665 - 6669 range)"),
    (6667, "IRC", "Internet Relay Chat (6665 - 6669 range)"),
    (6668, "IRC", "Internet Relay Chat (6665 - 6669 range)"),
    (6669, "IRC", "Internet Relay Chat (6665 - 6669 range)"),
    (6679, "IRC over SSL", "Internet Relay Chat"),
    (6697, "IRC over SSL", "Internet Relay Chat"),
    (6699, "Napster", "Peer-to-peer file-sharing application"),
    (6881, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6882, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6883, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6884, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6885, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6886, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6887, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6888, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6889, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6890, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6891, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6892, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6893, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6894, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6895, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6896, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6897, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6898, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6899, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6900, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6901, "BitTorrent / Windows Live Messenger", "Part of BitTorrent's most often used range (6881 - 6999 range) / Part of Windows Live Messenger alternatively: MSN Messenger (6891 - 6901 range)"),
    (6902, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6903, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6904, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6905, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6906, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6907, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6908, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6909, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6910, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6911, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6912, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6913, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6914, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6915, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6916, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6917, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6918, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6919, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6920, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6921, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6922, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6923, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6924, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6925, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6926, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6927, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6928, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6929, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6930, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6931, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6932, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6933, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6934, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6935, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6936, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6937, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6938, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6939, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6940, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6941, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6942, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6943, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6944, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6945, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6946, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6947, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6948, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6949, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6950, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6951, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6952, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6953, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6954, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6955, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6956, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6957, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6958, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6959, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6960, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6961, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6962, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6963, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6964, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6965, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6966, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6967, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6968, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6969, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6970, "BitTorrent / Quicktime", "Part of BitTorrent's most often used range (6881 - 6999 range) / QuickTime streaming server"),
    (6971, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6972, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6973, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6974, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6975, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6976, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6977, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6978, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6979, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6980, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6981, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6982, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6983, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6984, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6985, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6986, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6987, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6988, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6989, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6990, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6991, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6992, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6993, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6994, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6995, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6996, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6997, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6998, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (6999, "BitTorrent", "Part of BitTorrent's most often used range (6881 - 6999 range)"),
    (7000, "Cassandra", "Inter-node communication within the cluster on Apache Cassandra"),
    (7001, "Cassandra", "SSL-enabled inter-node communication within the cluster on Apache Cassandra"),
    (7210, "MaxDB", "MaxDB default port"),
    (7199, "Cassandra JMX", "Java Management Extensions on Apache Cassandra"),
    (7473, "Neo4j", "Neo4j db default port"),
    (7474, "Neo4j", "Neo4j db default port"),
    (7574, "Solr", "Solr db default port"),
    (7648, "CU-SeeMe", "Internet video conferencing client made by Cornell University"),
    (7649, "CU-SeeMe", "Internet video conferencing client made by Cornell University"),
    (7687, "Neo4j", "Neo4j db default port"),
    (8000, "Internet Radio", "Commonly choice of alternate HTTP port for web applications"),
    (8080, "HTTP Proxy", "Common web proxy server ports: 80, 8080, 3128, 6588"),
    (8086, "Kaspersky AV", "Kaspersky AV Control Center"),
    (8087, "Kaspersky AV / Riak", "Kaspersky AV Control Center / RiakDB default port"),
    (8098, "Riak", "RiakDB default port"),
    (8091, "Couchbase", "Couchbase database server default port"),
    (8118, "Privoxy", "Advertisement-filtering Web proxy"),
    (8200, "VMware Server", "VMware vSphere Fault Tolerance"),
    (8222, "VMware Server", "VMware Server Management User Interface (insecure Web interface)."),
    (8500, "(Multiple uses)", "Usually (but not guaranteed): Adobe ColdFusion / Flight Message Transfer Protocol"),
    (8529, "ArangoDB", "ArangoDB default port"),
    (8767, "Teamspeak", "VoIP communication system for online gaming"),
    (8866, "Bagle.B", "Possibly computer worm"),
    (8983, "Solr", "Solr db default port"),
    (9042, "Cassandra", "Apache Cassandra, a NoSql database"),
    (9100, "PDL", "PDL Data Stream, used for printing to certain network printers"),
    (9101, "Bacula", "For automating backup tasks"),
    (9102, "Bacula", "For automating backup tasks"),
    (9103, "Bacula", "For automating backup tasks"),
    (9119, "MXit", "MXit Instant Messaging (deprecated)"),
    (9200, "Elasticsearch", "Elasticsearch database default port"),
    (9300, "Elasticsearch", "Elasticsearch database default port"),
    (9800, "WebDAV", "Web-based Distributed Authoring and Versioning, an extension of HTTP"),
    (9898, "Dabber", "Possibly computer worm (Sasser)"),
    (9999, "Urchin", "Urchin Web Analytics"),
    (10000, "(Multiple uses)", "Usually (but not guaranteed Network Data Management Protocol / applications): Webmin / BackupExec / Viatalk ; gaming: The Matrix Online, Dungeon Fighter"),
    (10113, "NetIQ", "NetIQ Endpoint"),
    (10114, "NetIQ", "NetIQ Qcheck"),
    (10115, "NetIQ", "NetIQ Endpoint"),
    (10116, "NetIQ", "NetIQ VoIP Assessor"),
    (10161, "SNMP-agents (encrypted)", "Simple network management protocol; agents communicate on this port"),
    (10162, "SNMP-trap (encrypted)", "Simple network management protocol; listens for asynchronous traps"),
    (11371, "OpenPGP", "OpenPGP HTTP Keyserver"),
    (12345, "NetBus", "Possibly NetBus remote administration tool (Trojan horse)"),
    (13720, "NetBackup", "NetBackup request daemon"),
    (13721, "NetBackup", "NetBackup request daemon"),
    (14567, "Battlefield", "Gaming"),
    (15118, "Dipnet / Oddbob", "Possibly a trojan horse"),
    (19226, "AdminSecure", "Panda Software AdminSecure Communication Agent"),
    (19638, "Ensim", "Ensim Control Panel"),
    (20000, "Usermin", "Web email interface for regular non-root users"),
    (24800, "Synergy", "Keyboard/mouse sharing software"),
    (25999, "Xfire", "Communication tool for gamers (deprecated)"),
    (27015, "Half-Life", "Gaming"),
    (27017, "MongoDB", "NoSql database"),
    (27018, "MongoDB", "NoSql database"),
    (27019, "MongoDB", "NoSql database"),
    (27374, "Sub7", "Possibly a trojan horse"),
    (28015, "RethinkDB", "Rethink database default port"),
    (28017, "MongoDB", "NoSql database"),
    (28960, "Call of Duty", "Gaming"),
    (29015, "RethinkDB", "Rethink database default port"),
    (31337, "Back Orifice", "Possibly remote administration tool used for Trojan horses"),
    (39013, "SAP HANA", "SAP HANA db default port"),
    (49896, "Oracle Clusterware", "CRS daemon default port"),
    (50000, "IBM Db2", "IBM Db2 default port"),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
    (0, "", ""),
];

pub const PORT_FUZZING_COMMANDS: [&[u8]; 3] = [b"info\n", b"help\n", b"version\n"];
